# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_connector.client_pb2 as client__pb2


class CommandHandlerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendCommand = channel.unary_unary(
        '/CommandHandler/SendCommand',
        request_serializer=client__pb2.Command.SerializeToString,
        response_deserializer=client__pb2.Empty.FromString,
        )


class CommandHandlerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommandHandlerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendCommand': grpc.unary_unary_rpc_method_handler(
          servicer.SendCommand,
          request_deserializer=client__pb2.Command.FromString,
          response_serializer=client__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CommandHandler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
