# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63lient.proto\"\xca\x01\n\x07\x43ommand\x12)\n\x0b\x63ommandType\x18\x01 \x01(\x0e\x32\x14.Command.CommandType\"\x93\x01\n\x0b\x43ommandType\x12\x0b\n\x07\x46orward\x10\x00\x12\x0c\n\x08\x42\x61\x63kward\x10\x01\x12\x08\n\x04Left\x10\x02\x12\t\n\x05Right\x10\x03\x12\x0f\n\x0b\x46orwardLeft\x10\x04\x12\x10\n\x0c\x46orwardRight\x10\x05\x12\x10\n\x0c\x42\x61\x63kwardLeft\x10\x06\x12\x11\n\rBackwardRight\x10\x07\x12\x0c\n\x08ShutDown\x10\x08\"\x07\n\x05\x45mpty23\n\x0e\x43ommandHandler\x12!\n\x0bSendCommand\x12\x08.Command\x1a\x06.Empty\"\x00\x62\x06proto3')
)



_COMMAND_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='Command.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Forward', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Backward', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Left', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Right', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ForwardLeft', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ForwardRight', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BackwardLeft', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BackwardRight', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ShutDown', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=72,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_COMMAND_COMMANDTYPE)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandType', full_name='Command.commandType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMAND_COMMANDTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=219,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=228,
)

_COMMAND.fields_by_name['commandType'].enum_type = _COMMAND_COMMANDTYPE
_COMMAND_COMMANDTYPE.containing_type = _COMMAND
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  ))
_sym_db.RegisterMessage(Command)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)



_COMMANDHANDLER = _descriptor.ServiceDescriptor(
  name='CommandHandler',
  full_name='CommandHandler',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=230,
  serialized_end=281,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendCommand',
    full_name='CommandHandler.SendCommand',
    index=0,
    containing_service=None,
    input_type=_COMMAND,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMANDHANDLER)

DESCRIPTOR.services_by_name['CommandHandler'] = _COMMANDHANDLER

# @@protoc_insertion_point(module_scope)
